.TH GQRX "1" "November 1, 2020" "gqrx 2.13.3" "User Commands"
.SH NAME
gqrx \- Software Defined Radio GUI application
.SH DESCRIPTION
Gqrx is a software defined radio (SDR) receiver implemented using GNU Radio and
the Qt GUI toolkit. It works with hardware supported by gr-osmosdr, including
Funcube Dongle, RTL-SDR, Airspy, HackRF, BladeRF, RFSpace, USRP and SoapySDR.
.PP
Gqrx can operate as an AM/FM/SSB receiver with audio output or as an FFT-only
instrument. There are also various hooks for interacting with external
applications using network sockets.
.SH SEE ALSO
https://gqrx.dk/
