.TH GQRX "1" "February 2012" "gqrx-sdr 1.9.237" "User Commands"
.SH NAME
gqrx \- Software Defined Radio graphical user interface application.
.SH DESCRIPTION
AM, FM and SSB receiver powered by GNU Radio and Qt
.PP
Waterfall spectrum display and user interface elements from
Moe Wheatley's Cutesdr program, combined with a gnuradio signal
processing engine and hardware support for the FUNcube Dongle
receiver hardware.
.PP
.SH SEE ALSO
http://gqrx.dk/
