#!/usr/bin/env lua

local inp = io.popen("git --no-pager log")
local line = inp:read("*l")

local first = true

local function update_version()
	local version = io.popen("git describe --tags --always"):read("*l")
	local control = {}
	
	for line in io.lines("debian/control") do
		
		if line:match("^Version: .-$") then
			line = string.format("Version: %s", version)
			line = line:gsub("%-g", "+git")
		end
		
		table.insert(control, line)
	end
	
	io.open("debian/control", "w"):write(table.concat(control, "\n"))
end
update_version()

while line ~= nil do
	local hash = line:match("commit ([A-z0-9]+)")
	local version = io.popen("git describe --tags --always " .. hash):read("*l"):gsub("%-g", "+git")
	version = version:sub(2)
	
	if not version:match("%d+%.%d+") then
		version = "0.0-0+git" .. hash:sub(1,6)
	end
	
	if first then first = false else print() end
	print(string.format("gqrx (%s) unstable; urgency=low", version))
	
	local typ, author = inp:read("*l"):match("(%a+):%s+(.+)")
	
	if typ:lower() == "merge" then
		typ, author = inp:read("*l"):match("(%a+):%s+(.+)")
		assert(typ:lower() == "author")
	end
	
	local date = inp:read("*l"):match("Date:%s+(.+)")
	local msgs = {}
	
	-- fix the date
	local day, month, date, time, year, offset = date:match("(.+)%s+(.+)%s+(.+)%s+(.+)%s+(.+)%s+(.+)")
	date = string.format("%s, %s %s %s %s %s", day, date, month, year, time, offset)
	-- /fix
	
	assert(inp:read("*l") == "")
	while true do
		line = inp:read("*l")
		if line == nil or line == "" then break end
		table.insert(msgs, line:match("%s+(.+)"))
	end
	
	print()
	for k,v in pairs(msgs) do
		print(string.format("  * %s", v))
	end
	print()
	
	print(string.format(" -- %s  %s", author, date))
	line = inp:read("*l")
end



--[[
gqrx (1.0git) unstable; urgency=low

  * change details
  * even more change details

 -- Kate Adams <self@kateadams.eu>  Thu, 30 Jan 2014 01:27:00 +0000
]]
