/*
 * Copyright (C) 2013 Bastian Bloessl <bloessl@ccs-labs.org>
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rds
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RDS_API_H
#define INCLUDED_RDS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rds_EXPORTS
#define RDS_API __GR_ATTR_EXPORT
#else
#define RDS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RDS_API_H */
